language: python

python:
  - "3.6"
  
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install psycopg2-binary

services:
  -postgresql

before_script:
  - psql -c 'create database sendit_test;' -U postgres
  - export DATABASE_TEST="dbname='sendit_test' host='localhost' port='5432' user='postgres' password=''"
  - export FLASK_ENV=testing


script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls


# safelist



