language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=app

services:
  -postresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

after_success:
  - coveralls


# safelist



